import React, { Suspense, useEffect, useRef, useState } from "react";
import { useTranslation } from "react-i18next";

import LazyWorkspaceFallback from "./LazyWorkspaceFallback";
import TitleDuplicateAssistBridge from "./TitleDuplicateAssistBridge";
import { useApp, useAppActions } from "@/store/AppContext";
import { canWriteNote } from "@/lib/notePermissions";
import { consumeNewNoteTitleFocus } from "@/lib/noteTitleFocus";
import type { NoteSplitHeadingLevel } from "@/lib/noteSplit";
import {
  getCachedPreferredNoteSplitLevel,
  resolvePreferredNoteSplitLevel,
  schedulePreferredNoteSplitLevel,
} from "@/lib/noteSplitAnalysis";
import type { Note } from "@/types";

const LazyFormatAwareEditorPane = React.lazy(() => import("./FormatAwareEditorPane"));
const LazyNoteSplitDialog = React.lazy(() => import("./NoteSplitDialog"));

/**
 * 文档拆分运行时外壳。
 *
 * 标题扫描只服务于可选的“拆分文档”入口，不应阻塞每次笔记切换。首次打开把扫描安排
 * 到浏览器空闲阶段；A → B → A 返回同一版本时直接复用缓存结果。
 *
 * 编辑器主体通过 React.lazy 独立成工作区 chunk。未登录时 App 虽然会解析这个轻量壳，
 * 但不会下载 Tiptap、CodeMirror、导出和附件预览等高成本依赖。
 */
export default function EditorPaneRuntime() {
  const { state } = useApp();
  const actions = useAppActions();
  const { t } = useTranslation();
  const activeNote = state.activeNote;
  const editorRootRef = useRef<HTMLDivElement>(null);
  const [preferredLevel, setPreferredLevel] = useState<NoteSplitHeadingLevel | null>(null);
  const [dialogOpen, setDialogOpen] = useState(false);

  useEffect(() => {
    setDialogOpen(false);
    setPreferredLevel(null);

    const note = activeNote;
    if (!note) return;

    const cached = getCachedPreferredNoteSplitLevel(note);
    if (cached.hit) {
      setPreferredLevel(cached.level);
      return;
    }

    return schedulePreferredNoteSplitLevel(note, setPreferredLevel);
    // Deliberately analyze only when a note is opened. Re-running after every debounced save would
    // put the full-document scan back onto the editing path that this optimization removes.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [activeNote?.id]);

  useEffect(() => {
    const note = activeNote;
    if (!note || !consumeNewNoteTitleFocus()) return;

    // Only consume the request for the default titles generated by the quick-create flow.
    // This prevents a stale/cancelled create attempt from stealing focus when the user opens
    // an unrelated existing note before the short-lived request expires.
    const isDefaultNewTitle = note.title === t("common.untitledNote")
      || (note.contentFormat === "markdown" && note.title === "无标题 Markdown");
    if (!isDefaultNewTitle) return;

    let frameId: number | null = null;
    let timeoutId: number | null = null;
    let observer: MutationObserver | null = null;

    const cleanup = () => {
      if (frameId !== null) cancelAnimationFrame(frameId);
      if (timeoutId !== null) window.clearTimeout(timeoutId);
      observer?.disconnect();
      frameId = null;
      timeoutId = null;
      observer = null;
    };

    const focusTitle = (): boolean => {
      const root = editorRootRef.current;
      if (!root) return false;
      const title = root.querySelector<HTMLTextAreaElement>(
        "[data-mobile-editor-title] textarea, [data-markdown-mobile-title] textarea",
      );
      if (!title || title.disabled || title.readOnly) return false;
      title.focus({ preventScroll: true });
      title.select();
      return document.activeElement === title;
    };

    // The editor body is lazy-loaded. Usually it is already mounted, but on the first open the
    // Suspense chunk can arrive after this parent effect, so wait for the title field instead of
    // relying on a fragile fixed delay.
    frameId = requestAnimationFrame(() => {
      if (focusTitle()) return;
      const root = editorRootRef.current;
      if (!root) return;
      observer = new MutationObserver(() => {
        if (focusTitle()) cleanup();
      });
      observer.observe(root, { childList: true, subtree: true });
      timeoutId = window.setTimeout(cleanup, 3_000);
    });

    return cleanup;
  }, [activeNote?.id, t]);

  const handleApplied = (updated: Note) => {
    actions.setActiveNote(updated);
    actions.updateNoteInList({
      id: updated.id,
      title: updated.title,
      contentText: updated.contentText,
      updatedAt: updated.updatedAt,
      version: updated.version,
      notebookId: updated.notebookId,
      workspaceId: updated.workspaceId,
    });
    actions.updateNoteTab({
      id: updated.id,
      title: updated.title,
      updatedAt: updated.updatedAt,
      contentFormat: updated.contentFormat,
      isLocked: updated.isLocked,
      isTrashed: updated.isTrashed,
      notebookId: updated.notebookId,
    });
    // This scan follows an explicit split transaction, not a routine note switch, so resolving it
    // synchronously keeps the command state accurate without affecting navigation latency.
    setPreferredLevel(resolvePreferredNoteSplitLevel(updated));
    actions.refreshNotes();
    actions.refreshNotebooks();
  };

  const supportedFormat = activeNote?.contentFormat === "markdown"
    || activeNote?.contentFormat === "tiptap-json";
  const canSplit = !!(
    activeNote
    && preferredLevel
    && supportedFormat
    && !activeNote.isLocked
    && !activeNote.isTrashed
    && canWriteNote(activeNote)
  );

  return (
    <div ref={editorRootRef} className="relative flex h-full min-h-0 flex-col overflow-hidden">
      <TitleDuplicateAssistBridge rootRef={editorRootRef} />

      <Suspense fallback={<LazyWorkspaceFallback label="正在加载编辑器…" />}>
        <LazyFormatAwareEditorPane
          canSplitDocument={canSplit}
          onSplitDocument={() => setDialogOpen(true)}
        />
      </Suspense>

      {dialogOpen && activeNote && preferredLevel && (
        <Suspense fallback={null}>
          <LazyNoteSplitDialog
            open
            note={activeNote}
            notebooks={state.notebooks || []}
            preferredLevel={preferredLevel}
            onClose={() => setDialogOpen(false)}
            onApplied={handleApplied}
          />
        </Suspense>
      )}
    </div>
  );
}
