from pathlib import Path
import base64, gzip, sys
path = Path(sys.argv[1])
text = path.read_text()
start = text.index("new_upsert = r'''function buildTrackedUpsertStatement")
end = text.index("new_verify = r'''", start)
replacement = gzip.decompress(base64.b64decode("H4sIAD9Ic2oC/91ZW4/bRBR+z6+YRpViQ7AWJHjIdncVErdNm8sSewvVdpX1OpON22Sc9Yy7DUsk3oBHJCQe4AHeeEI8IuDncP0XzM32+Jb1qoCAVVXZ43POnDlzLt85QfByEq4wDAjYA0Gj0ZiFyCWej8BZ6C2mnbmDzqGFnBWe+8QiDoFLiIjmoVVIWuCqBkAQot60BTAJPHS+SxeIc7aAQ2cJ1UXXX4RLhFvAdoJzSDr89fiEfVoF3tIJ1g/huhMRCT7xOfAvW2AMXT+Y3hHrTRCiZ8i/RPvs+5lD3LkFL0KIXLolCpdnMNitbfQW6J7FGnNVXR9hAs7WTDl6XAQvwcBZicMYUkNjSVc08aKDvX1wLJ4NRJma8hwnur4by0v0pzJHZ0+hS4xZ4C9NRLWFWIrPnVLdiCnEN2NaRnLFJypTKGxQs6nku5zUmwHtVqSt4KY3MKdG48ezLhYegYc+JucBxAPvPHDY5ZpB4AeapAagbr3T79nm5PDeZNC7N27bvdFwcjjuDdrjx5OH5uNJZ9Q/GgzpR8vqDe/Vmwnnb198++tXH/3+9Te//fTDL999yrzhNXozcApI4LjP6G2BXz/58I8vP/z5+x//+OzbXz7+XOF+c2cneblSHUfYLF6I7N4CiQHAJuKVptjw/wNIwgBFtyaZHeQjz3UWj5xFCKURm3ITaiqF+ETnTrdRLxi+8DChJzl0AmeJ6YX8TTd6a1c9AWV5TsOyispC40Th+Lxj6gZbfLLU5aXOid+LhWpm5BwnOuNJxcnMCzA5VIOlxI7HOyLwhR2EAfHFogVOe0PLHNugN7RHbIW69mQlfXuyjJx7QlWZuDxxYZA4OXdXnqzqTVCPXYu9JBqk3+47eK64K5eQSjeMXOz00ENcrh945x7ilmevQik45a9pQdGnzhy6z3C4rCufdeXZMvtmxwYHTf6v1XqKfXQmXtIS+V+nbZn5VQDevW8OgRsGAc2FE8JzsHH76iL0CexN6Zo382CgZa5I34CeBYZH/X6RSJuJbHiIFQ84bRSRmH3LBI1wNXWKKcxh919whrKPXHviT7jFtfTGetXDMOEFyweppbvj0QBo8qZf10HbAhjCaYqmb961wYNRbwjyZ86kS3pmKiGtcEaFERNTEn85bXMJ4vTaW5DEGxrlB6d5YxlPfQ9pddAedkFd39RSinVGw7v9HrWEdm288gjVQXcEjg67bTvtNpZpZ+OVqtM325atFdx3pYRiZBNAgSDzvU7/qGt2s7Q5Uj3PnU8LVOVEYO5rgQQZbm3CWDtH47E5tCd2b2BadntweCo4VryWtWSqB1ESZ+ZuppaSGiyXH1ijoSGAmDdba8ldxKfBc+eNN9/SMGd9QINHJYqpBg6ZU8d6oe00xTOhu7vSlVOG07dIVktdQmcYRrpoiw8nTVlgL0IvgALbUhu8zpY3FDLWamn0e8SBcSHq/YdB7hTOII24qQUXs1iABYkk3t+GdxOkkGCXssqvVHClcj9n9f56ZhFUgqZAYWPuYE3dQF7WAcXsi4V8aVXDPRJjUCYVYXg8/5D1iAoI6EtOY+wvYdF5I0ah0gGog9EjczzudSnaBdZjyzYH4FG7f2SKGG6Bej3ZVcQbM49iaU5nzLwFoclQ3fFWGXj0kLsIpzAykS50yaferbk2zhTlVKcqUPTRbOG5hLYJlFkexFhAdE7mYB/sSHOcxvmV59TbVxGlyOJNlsJPI8tQ2uHIvs/6hAoorkItS2U47faVYmVunYwAXdVKp0Uu4xSqPH6nVpFQjRu7flBPiysrVKW19HoNFZFMjfhCNplMLYLwhhlsIOvFv7iD/9836um27q9sTNM4iCqwvfIWMf4HetqCDCKTUbUWkEFh/piGShwdqv0ZPUMM9gWuZWIKMFqq52MYa2u/wkmNDMuWnoj+MVQc8akNZYmG5c0ZzQVczJburEC/qq3NNUgz3+FUbFySo9XS1hybVZuWfNlMhN6wWylvVTI3JXoVJqKcJmljttNlOhyuVzFwp1A3G83NG2P69HZVwbKD18gFccEJ4IwG4dxmcz8YVx7qt1gtNs7UWVFMRHO+Q9VwMGyLhd3KhUj0Bt77mWHvIc3kHoZ3nvvedF+FvzIN7AHn0vGINIFUw6AdRrAeOGh9R+SXxBJb8XjWZKp+m30BhE9lP799vFRTA6RSQqup8aB4nfDQQg8bjbvmGLz9OLe7dKpj1VWyTsIdgWfimR8AbQEJ8GczDNkvBju70fOdyNASPsYfXo1qS3xveqqA4KjycwQtZWAKgqAmJDRjSTlBMsw5k1KZ4sGtKOxJtZcLkkMJHPDBB+BqIwfJYqouaSM0vLdHT5uM2G8+ZH+ZMbuYXGYH62LkLgbrKeLUXH37ZD2Zosdz9GiSnqm8f231La3AYqCEJV5tFtbHqgX4pYrwdYU4rWiZiCp1+Ga1uLwe37QmJ5PHAlkyeRXhDT6e3Hbuly/22aIvg7H4zCILHEeI/+XKfaWyz4IlUb5WqHQeFlRGAtXRQBEiiAZgMn8J4zRF/yiswx9TwLYAKmyBCzzDZlNoghwU9FCKIHiaAZjmCzxjKVrpAOWvecoPnEmJUGYTemE9hy+gGxIYC8MKs+gpGHJpNBq1AJ7DFxMf0Tojq9FqLSFPY+sY8EkEZ55cGa8cPEE5GLRyvIDNvcZsBsYGmLghBKPkx/ZXQaMan16r/QmpMFRJpB8AAA==")).decode()
text = text[:start] + replacement + text[end:]
old_map = '      const statements = batch.rows.map((row) => buildTrackedUpsertStatement({\n        runId: input.claim.runId,\n        tableName: sourceTable.name,\n        columns,\n        primaryKeyColumns: sourceTable.primaryKeyColumns,\n        row,\n        deferredSelfColumns: deferredNames,\n        batchSequence,\n      }));\n'
new_map = '      const statements = batch.rows.flatMap((row) => [\n        buildChangeSnapshotStatement({\n          runId: input.claim.runId,\n          tableName: sourceTable.name,\n          columns,\n          primaryKeyColumns: sourceTable.primaryKeyColumns,\n          row,\n          batchSequence,\n        }),\n        buildUpsertStatement({\n          tableName: sourceTable.name,\n          columns,\n          primaryKeyColumns: sourceTable.primaryKeyColumns,\n          row,\n          deferredSelfColumns: deferredNames,\n        }),\n        buildMigratedSnapshotStatement({\n          runId: input.claim.runId,\n          tableName: sourceTable.name,\n          columns,\n          primaryKeyColumns: sourceTable.primaryKeyColumns,\n          row,\n        }),\n      ]);\n'
if old_map not in text:
    raise SystemExit("tracked-upsert map anchor missing")
text = text.replace(old_map, new_map, 1)
path.write_text(text)
