/**
 * Note and block backlink extraction.
 *
 * Tiptap links inherit the closest supported node blockId. Markdown links use
 * the persisted `^blk_xxx` suffix generated by noteBlocks.ts, so both editors
 * produce sourceBlockId + targetBlockId relations.
 *
 * Parsing is intentionally isolated from SQLite repositories so PostgreSQL
 * runtime modules can import it without installing SQLite startup guards.
 */

import { noteLinksRepository } from "../repositories/noteLinksRepository";
import type { NoteLinkEntry } from "../repositories/types";
import { extractNoteLinksFromContent } from "./noteContentReferences";

export { extractNoteLinksFromContent } from "./noteContentReferences";

export function syncNoteLinks(
  _db: unknown,
  userId: string,
  sourceNoteId: string,
  content: string,
): void {
  try {
    const links: NoteLinkEntry[] = extractNoteLinksFromContent(content).filter(
      (link) => !(link.targetNoteId === sourceNoteId.toLowerCase() && !link.targetBlockId),
    );
    noteLinksRepository.replaceLinksForSource(userId, sourceNoteId, links);
  } catch (error) {
    console.warn("[syncNoteLinks] failed:", error instanceof Error ? error.message : error);
  }
}

export function getBacklinks(
  _db: unknown,
  userId: string,
  targetNoteId: string,
  limit = 50,
) {
  // Keep the synchronous ACL dependency lazy. Importing middleware/acl installs
  // SQLite notebook-tree guards, which must never happen when PostgreSQL runtime
  // only needs the pure link parser above.
  const { hasPermission, resolveNotePermission } = require("../middleware/acl") as typeof import("../middleware/acl");
  return noteLinksRepository
    .getBacklinks(userId, targetNoteId, Math.min(Math.max(limit * 3, limit), 600))
    .filter((item) => hasPermission(resolveNotePermission(item.sourceNoteId, userId).permission, "read"))
    .slice(0, limit);
}
