import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { serve } from "@hono/node-server";
import { Hono } from "hono";
import JSZip from "jszip";
import { openRegistry } from "./schema.js";

const dataRoot = path.resolve(process.env.REGISTRY_DATA || "data"); fs.mkdirSync(path.join(dataRoot, "artifacts"), { recursive: true });
const db = openRegistry(path.join(dataRoot, "registry.db")); const app = new Hono();
const registryPrivateKey = process.env.REGISTRY_SIGNING_PRIVATE_KEY?.replace(/\\n/g, "\n") || "";
const publicBase = process.env.REGISTRY_PUBLIC_URL || "http://localhost:4310";
const sessionSecret = process.env.REGISTRY_SESSION_SECRET || "development-only";
const now = () => new Date().toISOString();
const canonical = (value: any): string => value === null || typeof value !== "object" ? JSON.stringify(value) : Array.isArray(value) ? `[${value.map(canonical).join(",")}]` : `{${Object.keys(value).sort().map((key) => `${JSON.stringify(key)}:${canonical(value[key])}`).join(",")}}`;
const digest = (bytes: Buffer) => crypto.createHash("sha256").update(bytes).digest();
const token = (id: string) => `${Buffer.from(id).toString("base64url")}.${crypto.createHmac("sha256", sessionSecret).update(id).digest("base64url")}`;
function actor(c: any): string { const raw = c.req.header("authorization")?.replace(/^Bearer\s+/i, "") || ""; const [encoded, mac] = raw.split("."); if (!encoded || !mac) throw new Error("authentication required"); const id = Buffer.from(encoded, "base64url").toString(); if (!crypto.timingSafeEqual(Buffer.from(mac), Buffer.from(crypto.createHmac("sha256", sessionSecret).update(id).digest("base64url")))) throw new Error("invalid session"); return id; }
function member(publisher: string, developer: string): void { if (!db.prepare("SELECT 1 FROM publisher_members WHERE publisherId=? AND developerId=? AND role IN ('owner','admin')").get(publisher, developer)) throw new Error("publisher access denied"); }
function signDocument(document: Record<string, unknown>): string { if (!registryPrivateKey) throw new Error("REGISTRY_SIGNING_PRIVATE_KEY is required"); return crypto.sign(null, Buffer.from(canonical(document)), registryPrivateKey).toString("base64"); }
function transaction(action: () => void): void { db.exec("BEGIN IMMEDIATE"); try { action(); db.exec("COMMIT"); } catch (error) { db.exec("ROLLBACK"); throw error; } }

app.get("/health", (c) => c.json({ ok: true, service: "nowen-extension-registry" }));
app.get("/oauth/github/start", (c) => { const state = crypto.randomBytes(24).toString("hex"); c.header("Set-Cookie", `oauth_state=${state}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=600`); return c.redirect(`https://github.com/login/oauth/authorize?client_id=${encodeURIComponent(process.env.GITHUB_CLIENT_ID || "")}&scope=read:user&state=${state}`); });
app.get("/oauth/github/callback", async (c) => {
  const state = c.req.query("state"); if (!state || !c.req.header("cookie")?.includes(`oauth_state=${state}`)) return c.json({ error: "invalid oauth state" }, 400);
  const exchange = await fetch("https://github.com/login/oauth/access_token", { method: "POST", headers: { Accept: "application/json", "Content-Type": "application/json" }, body: JSON.stringify({ client_id: process.env.GITHUB_CLIENT_ID, client_secret: process.env.GITHUB_CLIENT_SECRET, code: c.req.query("code") }) });
  const access = await exchange.json() as any; const profile = await fetch("https://api.github.com/user", { headers: { Authorization: `Bearer ${access.access_token}`, "User-Agent": "Nowen-Registry" } }).then((response) => response.json()) as any;
  const id = crypto.randomUUID(); db.prepare("INSERT INTO developers(id,githubId,login,avatar,createdAt) VALUES (?,?,?,?,?) ON CONFLICT(githubId) DO UPDATE SET login=excluded.login,avatar=excluded.avatar").run(id, String(profile.id), profile.login, profile.avatar_url || null, now());
  const developer = db.prepare("SELECT id FROM developers WHERE githubId=?").get(String(profile.id)) as { id: string }; return c.json({ token: token(developer.id), login: profile.login });
});
app.post("/v2/publishers", async (c) => { try { const developer = actor(c); const body = await c.req.json() as any; if (!/^[a-z0-9][a-z0-9-]{1,63}$/.test(body.id)) throw new Error("invalid publisher id"); transaction(() => { db.prepare("INSERT INTO publishers(id,displayName,description,website,github,createdAt) VALUES (?,?,?,?,?,?)").run(body.id, body.displayName, body.description || "", body.website || null, body.github || null, now()); db.prepare("INSERT INTO publisher_members VALUES (?,?, 'owner')").run(body.id, developer); }); return c.json({ id: body.id }, 201); } catch (error) { return c.json({ error: String((error as Error).message) }, 400); } });
app.post("/v2/publishers/:id/keys", async (c) => { try { const developer = actor(c); member(c.req.param("id"), developer); const body = await c.req.json() as any; crypto.createPublicKey(body.publicKey); db.prepare("INSERT INTO publisher_keys(id,publisherId,publicKey,validFrom,validUntil) VALUES (?,?,?,?,?)").run(body.id, c.req.param("id"), body.publicKey, now(), body.validUntil || null); return c.json({ id: body.id }, 201); } catch (error) { return c.json({ error: (error as Error).message }, 400); } });
app.post("/v2/publishers/:id/keys/:key/revoke", async (c) => { try { member(c.req.param("id"), actor(c)); db.prepare("UPDATE publisher_keys SET state='revoked',revokedAt=? WHERE id=? AND publisherId=?").run(now(), c.req.param("key"), c.req.param("id")); return c.json({ success: true }); } catch (error) { return c.json({ error: (error as Error).message }, 400); } });

app.post("/v2/publish", async (c) => { try {
  const developer = actor(c); const form = await c.req.parseBody(); const artifact = form.artifact; if (!(artifact instanceof File)) throw new Error("artifact is required");
  const manifest = JSON.parse(String(form.manifest || "{}")); const signed = JSON.parse(String(form.signature || "{}")); member(manifest.publisher, developer);
  if (manifest.apiVersion !== 2 || !manifest.id.startsWith(`${manifest.publisher}.`) || !manifest.repository || !manifest.license) throw new Error("invalid V2 manifest");
  if (artifact.size > 20 * 1024 * 1024) throw new Error("artifact exceeds 20MB"); const bytes = Buffer.from(await artifact.arrayBuffer()); const sha256 = digest(bytes).toString("hex"); if (signed.sha256 !== sha256) throw new Error("checksum mismatch");
  const key = db.prepare("SELECT * FROM publisher_keys WHERE id=? AND publisherId=? AND state='active'").get(signed.keyId, manifest.publisher) as any; if (!key || !crypto.verify(null, digest(bytes), key.publicKey, Buffer.from(signed.signature, "base64"))) throw new Error("publisher signature invalid");
  if (db.prepare("SELECT 1 FROM extension_versions WHERE extensionId=? AND version=?").get(manifest.id, manifest.version)) throw new Error("immutable version already exists");
  const zip = await JSZip.loadAsync(bytes, { checkCRC32: true }); const names = Object.keys(zip.files); const forbidden = names.filter((name) => /(^|\/)(node_modules)(\/|$)|\.(node|exe|dll|so|dylib)$/i.test(name)); if (forbidden.length || names.length > 500 || !zip.file("manifest.json") || !zip.file(manifest.main)) throw new Error("security scan rejected package");
  const source = zip.file(manifest.main) ? await zip.file(manifest.main)!.async("string") : ""; const findings = ["child_process", "process.env", "require(", "node:fs"].filter((needle) => source.includes(needle)); if (manifest.runtime === "sandbox-js" && findings.length) throw new Error(`sandbox static scan rejected: ${findings.join(",")}`);
  const extensionDir = path.join(dataRoot, "artifacts", manifest.id); fs.mkdirSync(extensionDir, { recursive: true }); const artifactPath = path.join(extensionDir, `${manifest.version}.nowen-plugin`); fs.writeFileSync(artifactPath, bytes, { flag: "wx" }); const artifactUrl = `${publicBase}/v2/artifacts/${manifest.id}/${manifest.version}`; const at = now();
  transaction(() => { db.prepare(`INSERT INTO extensions(id,publisherId,name,description,repository,license,createdAt,updatedAt) VALUES (?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,description=excluded.description,repository=excluded.repository,license=excluded.license,updatedAt=excluded.updatedAt`).run(manifest.id, manifest.publisher, manifest.name, manifest.description || "", manifest.repository, manifest.license, at, at); db.prepare(`INSERT INTO extension_versions(extensionId,version,apiVersion,runtime,manifestJson,artifactPath,artifactUrl,sha256,publisherKeyId,signature,scanState,scanReportJson,publishedAt) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(manifest.id, manifest.version, 2, manifest.runtime, JSON.stringify(manifest), artifactPath, artifactUrl, sha256, signed.keyId, signed.signature, "passed", JSON.stringify({ files: names.length, staticFindings: findings }), at); });
  return c.json({ extensionId: manifest.id, version: manifest.version, sha256, scan: "passed" }, 201);
} catch (error) { return c.json({ error: (error as Error).message }, 400); } });

app.get("/v2/index.json", (c) => { const publishers = db.prepare("SELECT publisherId AS publisher,id AS keyId,publicKey,state,validFrom,validUntil FROM publisher_keys").all(); const extensionRows = db.prepare("SELECT * FROM extensions WHERE listed=1").all() as any[]; const extensions = extensionRows.map((extension) => ({ id: extension.id, publisher: extension.publisherId, name: extension.name, description: extension.description, trustLevel: extension.trustLevel, versions: (db.prepare("SELECT version,apiVersion,runtime,artifactUrl,sha256,publisherKeyId,signature,publishedAt,manifestJson FROM extension_versions WHERE extensionId=? ORDER BY publishedAt DESC").all(extension.id) as any[]).map(({ manifestJson, ...version }) => { const manifest = JSON.parse(manifestJson); return { ...version, nowen: manifest.engines.nowen, permissions: manifest.permissions, permissionConfig: manifest.permissionConfig, platforms: manifest.platforms, runtimePlatform: manifest.runtimePlatform, uiPlatform: manifest.uiPlatform }; }) })); const advisories = (db.prepare("SELECT * FROM security_advisories").all() as any[]).map(({ versionsJson, extensionId, ...item }) => ({ ...item, extensionId, versions: JSON.parse(versionsJson) })); const unsigned = { protocolVersion: 2, generatedAt: now(), publishers, extensions, advisories }; return c.json({ ...unsigned, signature: signDocument(unsigned) }); });
app.get("/v2/extensions/:id", (c) => { const extension = db.prepare("SELECT * FROM extensions WHERE id=? AND listed=1").get(c.req.param("id")); return extension ? c.json(extension) : c.json({ error: "not found" }, 404); });
app.get("/v2/artifacts/:id/:version", (c) => { const row = db.prepare("SELECT artifactPath FROM extension_versions WHERE extensionId=? AND version=?").get(c.req.param("id"), c.req.param("version")) as any; if (!row) return c.json({ error: "not found" }, 404); return new Response(fs.readFileSync(row.artifactPath), { headers: { "Content-Type": "application/zip", "Cache-Control": "public,max-age=31536000,immutable" } }); });
app.post("/v2/extensions/:id/reviews", async (c) => { try { const developer = actor(c); const body = await c.req.json() as any; const at = now(); db.prepare(`INSERT INTO extension_reviews(id,extensionId,version,developerId,rating,comment,createdAt,updatedAt) VALUES (?,?,?,?,?,?,?,?) ON CONFLICT(extensionId,version,developerId) DO UPDATE SET rating=excluded.rating,comment=excluded.comment,updatedAt=excluded.updatedAt`).run(crypto.randomUUID(), c.req.param("id"), body.version, developer, body.rating, String(body.comment || "").slice(0, 2000), at, at); return c.json({ success: true }); } catch (error) { return c.json({ error: (error as Error).message }, 400); } });
app.get("/v2/extensions/:id/reviews", (c) => c.json(db.prepare("SELECT version,rating,comment,createdAt,updatedAt FROM extension_reviews WHERE extensionId=? ORDER BY updatedAt DESC LIMIT 200").all(c.req.param("id"))));
app.post("/v2/extensions/:id/reports", async (c) => { try { const developer = actor(c); const body = await c.req.json() as any; const at = now(); db.prepare("INSERT INTO extension_reports VALUES (?,?,?,?,?,?, 'pending',?,?)").run(crypto.randomUUID(), c.req.param("id"), body.version || null, developer, body.reason, String(body.details || "").slice(0, 4000), at, at); return c.json({ success: true }, 201); } catch (error) { return c.json({ error: (error as Error).message }, 400); } });
app.post("/v2/admin/advisories", async (c) => { try { if (!process.env.REGISTRY_ADMIN_TOKEN || c.req.header("authorization") !== `Bearer ${process.env.REGISTRY_ADMIN_TOKEN}`) return c.json({ error: "admin access denied" }, 403); const body = await c.req.json() as any; if (!Array.isArray(body.versions) || !["warning", "revoked", "malicious"].includes(body.state) || !["warn", "disable"].includes(body.action)) throw new Error("invalid advisory"); const at = now(); db.prepare("INSERT INTO security_advisories(id,extensionId,versionsJson,state,severity,title,detailsUrl,action,createdAt,updatedAt) VALUES (?,?,?,?,?,?,?,?,?,?)").run(body.id || crypto.randomUUID(), body.extensionId, JSON.stringify(body.versions), body.state, body.severity, body.title, body.detailsUrl || null, body.action, at, at); return c.json({ success: true }, 201); } catch (error) { return c.json({ error: (error as Error).message }, 400); } });
app.post("/v2/telemetry", async (c) => { try { const body = await c.req.json() as any; if (!/^(install|update|uninstall|crash)$/.test(body.event) || !/^[a-z0-9]+(?:[.-][a-z0-9]+)+$/.test(body.extensionId)) throw new Error("invalid telemetry"); const day = new Date().toISOString().slice(0, 10); db.prepare(`INSERT INTO daily_extension_stats(day,extensionId,event,count) VALUES (?,?,?,1) ON CONFLICT(day,extensionId,event) DO UPDATE SET count=count+1`).run(day, body.extensionId, body.event); return c.json({ accepted: true, privacy: "aggregate-only" }, 202); } catch (error) { return c.json({ error: (error as Error).message }, 400); } });

if (import.meta.url === `file://${process.argv[1]?.replace(/\\/g, "/")}`) serve({ fetch: app.fetch, port: Number(process.env.PORT || 4310) });
export default app;
